---
- name: Update apt and install rsyslog
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - rsyslog
      - rsyslog-gnutls
      - rsyslog-relp
    state: present

- name: Copy rsyslog configuration file
  become: true
  ansible.builtin.template:
    src: "templates/01-graylog.conf.j2"
    dest: /etc/rsyslog.d/01-graylog.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart rsyslog

- name: Ensure rsyslog service is enabled
  become: true
  ansible.builtin.systemd:
    name: rsyslog
    enabled: true
  notify: Restart rsyslog
